### ISSUE TITLE
train_cartpole.py

### ISSUE THREAD

**Issue by ghost** [Silvicek/distributional-dqn#5]
Hi Silvicek,

  When I ran your train_cartpole.py, I got this error:

  Traceback (most recent call last):
  File "train_cartpole.py", line 40, in <module>
    main()
  File "train_cartpole.py", line 33, in main
    dist_params={'Vmin': 0, 'Vmax': 25, 'nb_atoms': 11}
  File "C:\distributional-dqn-master\distdeepq\simple.py", line 201, in learn
    dist_params=dist_params
  File "C:\distributional-dqn-master\distdeepq\build_graph.py", line 215, in build_train
    act_f = build_act(make_obs_ph, p_dist_func, num_actions, dist_params, scope=scope, reuse=reuse)
  File "C:\distributional-dqn-master\distdeepq\build_graph.py", line 132, in build_act
    observations_ph = make_obs_ph("observation")
  File "C:\distributional-dqn-master\distdeepq\simple.py", line 186, in make_obs_ph
    return U.BatchInput(env.observation_space.shape, name=name)
AttributeError: module 'baselines.common.tf_util' has no attribute 'BatchInput'

     Thanks for your help!
     W

**Comment by Silvicek** [comment]
Hi, sorry I didn't notice this earlier.
 The problem is that the baselines repository changes a lot and is backwards incompatible. You need to use my fork of baselines as described in README.

**Comment by ghost** [comment]
Thanks Silvicek for your help! It works now with your fork of baselines.
